name: Deploy to sandbox

on:
  push:
    branches:
      - testing-qa

jobs:
  vapor:
    name: sandbox
    runs-on: ubuntu-latest
    steps:
      - name: push event
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
            https://api.github.com/repos/webinarinc/Admin-Central/actions/workflows/qa.yaml/dispatches \
            -d '{ "ref": "testing-qa" }'
